### ISSUE TITLE
Selecting search result doesn't update coordinates

### ISSUE THREAD

**Issue by oliverroick** [gis-ops/latlon2clipboard#1]
When I select a result from the address search, the marker on the map is set to the correct location but the coordinates in the top-right corner still show the previous location, the same outdated coordinates are copied to the clipboard. 

**How to reproduce:**

- Search for an address (I used "SE265EQ", which is a post code in South London)
- Select first result

**Comment by TimMcCauley** [comment]
Thanks @oliverroick that was me being a little dull ;-) ;-)
